/// 389. Find the Difference
/// https://leetcode.com/problems/find-the-difference/
///
/// You are given two strings s and t.
//
/// String t is generated by random shuffling string s and then add one more
/// letter at a random position.
///
/// Return the letter that was added to t.

class Solution {
  String findTheDifference(String s, String t) {
    final aCode = 'a'.codeUnitAt(0);
    final count = List<int>.filled(100, 0);

    for (var i = 0; i < s.length; i++) {
      final code = s.codeUnitAt(i);
      count[code - aCode]++;
    }

    for (var i = 0; i < t.length; i++) {
      final code = t.codeUnitAt(i);
      count[code - aCode]--;

      if (count[code - aCode] < 0) {
        return t[i];
      }
    }

    return '';
  }
}
